### ISSUE TITLE
Levenshtein comparison is ignoring last characters of both strings

### ISSUE THREAD

**Issue by wseguin** [tylerjensen/FuzzyStrings#2]
"78135".LevenshteinDistance("75130") should be 2 (8,5 and 5,0), but returns 1.

however

"78135x".LevenshteinDistance("75130x") correctly returns 2.

**Comment by xjfnet** [comment]
"abc".LevenshteinDistance("ab12345") should be 5, but returns 4

**Comment by kimpenhaus** [comment]
There is a .NET core compatible [fork](https://github.com/rangp/fuzzystrings) which has a fix for this issue

**Comment by aranm** [comment]
If this pull request has been merged successfully, why is this issue not closed?

**Comment by kimpenhaus** [comment]
Because it is only fixed in the [fork](https://github.com/rangp/fuzzystrings) and not in this package. So in this package it it still a bug.
